### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by izbekiadam** [izbekiadam/wax#1]
Travis needed to support continuous integration.

**Comment by izbekiadam** [comment]
Travis added and working from 9f4ae54c8e2f899f17d083ce02d00f23cb51b97d

**Comment by micskeiz** [comment]
OK

**Comment by norbezz** [comment]
You can see on our [Wiki page](https://github.com/izbekiadam/wax/wiki/How-to-add-Travis-CI-to-project) how you can add Travis to your own project.
