### ISSUE TITLE
SonarQube

### ISSUE THREAD

**Issue by sokama** [izbekiadam/wax#2]
We need SonarQube for static analyzing

**Comment by micskeiz** [comment]
Please add a screenshot about SonarQube results for the project to the appropriate wiki page.

**Comment by izbekiadam** [comment]
The screenshots were there, but their links were broken. It's fixed now.

**Comment by norbezz** [comment]
[Wiki page](https://github.com/izbekiadam/wax/wiki/SonarQube) to SonarQube results.
